version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: challenge-poo-db
    environment:
      POSTGRES_DB: challenge-poo
      POSTGRES_USER: challenge-poo
      POSTGRES_PASSWORD: challenge-poo
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: challenge-poo-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: challenge-poo
      MONGO_INITDB_ROOT_PASSWORD: challenge-poo
      MONGO_INITDB_DATABASE: challenge-poo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mysql_data:
  mongodb_data: